invoice_due:
    pattern:  /calculateDueDate
    defaults: { _controller: TeclliureInvoiceBundle:Common:calculateDueDate }

search_customer:
    pattern: /searchCustomer
    defaults: { _controller: TeclliureInvoiceBundle:Common:searchCustomer }
    prefix:   /

search_contact:
    pattern: /searchContact
    defaults: { _controller: TeclliureInvoiceBundle:Common:searchContact }
    prefix:   /

search_customer_name:
    pattern: /searchCustomerName
    defaults: { _controller: TeclliureInvoiceBundle:Common:searchCustomerName }

update_prices:
    pattern: /updatePrices
    defaults: { _controller: TeclliureInvoiceBundle:Common:updatePrices }