parameters:
    teclliure_invoice_service.class: Teclliure\InvoiceBundle\Service\InvoiceService
    teclliure_common_service.class: Teclliure\InvoiceBundle\Service\CommonService
    teclliure_quote_service.class: Teclliure\InvoiceBundle\Service\QuoteService
    teclliure_delivery_note_service.class: Teclliure\InvoiceBundle\Service\DeliveryNoteService
    teclliure_payment_service.class: Teclliure\InvoiceBundle\Service\PaymentService
    doctrine_custom_checker.class: Teclliure\InvoiceBundle\Util\DoctrineCustomChecker
    teclliure_from_mail: 'send@example.net'

services:
  doctrine_custom_checker:
      class: "%doctrine_custom_checker.class%"
      arguments:
        em: "@doctrine.orm.entity_manager"

  common_service:
        class: "%teclliure_common_service.class%"
        arguments:
          em: "@doctrine.orm.entity_manager"
          config: "@craue_config"
          eventDispatcher: "@event_dispatcher"
          customChecker: "@doctrine_custom_checker"
        tags:
          - { name: "knp_paginator.injectable", alias: "knp_paginator" }


  invoice_service:
      class: "%teclliure_invoice_service.class%"
      arguments:
        em: "@doctrine.orm.entity_manager"
        config: "@craue_config"
        eventDispatcher: "@event_dispatcher"
        customChecker: "@doctrine_custom_checker"
      tags:
        - { name: "knp_paginator.injectable", alias: "knp_paginator" }

  quote_service:
        class: "%teclliure_quote_service.class%"
        arguments:
          em: "@doctrine.orm.entity_manager"
          config: "@craue_config"
          eventDispatcher: "@event_dispatcher"
          customChecker: "@doctrine_custom_checker"
        tags:
          - { name: "knp_paginator.injectable", alias: "knp_paginator" }

  delivery_note_service:
        class: "%teclliure_delivery_note_service.class%"
        arguments:
          em: "@doctrine.orm.entity_manager"
          config: "@craue_config"
          eventDispatcher: "@event_dispatcher"
          customChecker: "@doctrine_custom_checker"
        tags:
          - { name: "knp_paginator.injectable", alias: "knp_paginator" }

  payment_service:
        class: "%teclliure_payment_service.class%"
        arguments:
          em: "@doctrine.orm.entity_manager"
          config: "@craue_config"


  teclliure.form.type_extension.collection:
      class: Teclliure\InvoiceBundle\Form\Extension\CollectionTypeExtension
      tags:
          - { name: "form.type_extension", alias: "collection" }

  teclliure.form.type.common:
      class: Teclliure\InvoiceBundle\Form\Type\CommonType
      arguments:
          - @doctrine.orm.entity_manager

  teclliure.form.type.invoice:
        class: Teclliure\InvoiceBundle\Form\Type\InvoiceType
        arguments:
            - @doctrine.orm.entity_manager

  teclliure.form.type.quote:
        class: Teclliure\InvoiceBundle\Form\Type\QuoteType
        arguments:
            - @doctrine.orm.entity_manager

  teclliure.form.type.delivery_note:
          class: Teclliure\InvoiceBundle\Form\Type\DeliveryNoteType
          arguments:
              - @doctrine.orm.entity_manager

#  teclliure.common.mailer.subscriber:
#        class: Teclliure\InvoiceBundle\Listener\CommonMailerSubscriber
#        arguments:
#            mailer: @mailer
#            transport: @swiftmailer.transport.real
#            translator: @translator
#            pdfGenerator: "@knp_snappy.pdf"
#            templating: @templating
#            config: @craue_config
#            fromEmail: %teclliure_from_mail%
#        tags:
#            - { name: kernel.event_subscriber }
  teclliure.common.status.subscriber:
        class: Teclliure\InvoiceBundle\Listener\StatusChangeSubscriber
        arguments:
            - @common_service
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_subscriber }

  invoice_mailer:
        class: Teclliure\InvoiceBundle\Mailer\Mailer
        arguments:
            mailer: @mailer
            transport: @swiftmailer.transport.real
            translator: @translator
            pdfGenerator: "@knp_snappy.pdf"
            templating: @templating
            config: @craue_config
            fromEmail: %teclliure_from_mail%

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
        - { name: twig.extension }
#    teclliure_invoice.example:
#        class: %teclliure_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
